name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t rallycoding/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true rallycoding/react-test npm test

      - run: docker build -t piotrzrk/multi-client ./client
      - run: docker build -t piotrzrk/multi-nginx ./nginx
      - run: docker build -t piotrzrk/multi-server ./server
      - run: docker build -t piotrzrk/multi-worker ./worker

      - run: docker push piotrzrk/multi-client
      - run: docker push piotrzrk/multi-nginx
      - run: docker push piotrzrk/multi-server
      - run: docker push piotrzrk/multi-worker
